/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/sandbox/tests/fixtures/s3-native-local/wrangler.jsonc --include-runtime=false packages/sandbox/tests/fixtures/s3-native-local/worker-configuration.d.ts` (hash: ea041772cbf712cb152d7e1ac59685d5)
interface __BaseEnv_Env {
  EXPERIMENTAL_CLOUDFLARE_CONTAINER_IMAGES: Readonly<
    Record<string, Readonly<Record<string, string>>>
  >;
  SANDBOX: DurableObjectNamespace<import("./worker").S3NativeLocalSandbox>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
    durableNamespaces: "S3NativeLocalSandbox";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
