export const COMMAND_SESSION_FRAME_PREFIX = '__SANDBOX_SESSIONS__';

export function createCommandSessionScript(tempDir: string): string {
  const safeTempDir = shellQuote(tempDir);
  return [
    'set +H',
    'shopt -s expand_aliases',
    'unset HISTFILE',
    'export HISTFILE=/dev/null',
    `__sandbox_sessions_dir=${safeTempDir}`,
    `__sandbox_sessions_frame() { printf '${COMMAND_SESSION_FRAME_PREFIX}|%s|%s|%s|%s|%s\n' "$1" "$2" "$3" "$4" "$5"; }`,
    '__sandbox_sessions_base64_file() {',
    '  base64 < "$1" | tr -d \'\\n\'',
    '}',
    '__sandbox_sessions_emit_payload() {',
    '  local process_id="$1" stream="$2" data="$3" payload',
    '  if [[ -n "$data" ]]; then',
    "    payload=$(printf '%s' \"$data\" | base64 | tr -d '\\n')",
    '    __sandbox_sessions_frame PROCESS_OUTPUT "$process_id" "$stream" "$payload" ""',
    '  fi',
    '}',
    '__sandbox_sessions_emit_fifo() {',
    '  local process_id="$1" stream="$2" fifo="$3" stop_marker="$4" char buffer chunk emit_count',
    '  local marker_length=$' + '{#stop_marker}',
    '  buffer=""',
    '  while true; do',
    '    IFS= read -r -t 0.05 -N 1 char',
    '    if [[ -n "$char" ]]; then',
    '      buffer+="$char"',
    '      char=""',
    '      if [[ "$' + '{buffer: -$marker_length}" == "$stop_marker" ]]; then',
    '        chunk="$' + '{buffer:0:$' + '{#buffer}-$marker_length}"',
    '        __sandbox_sessions_emit_payload "$process_id" "$stream" "$chunk"',
    '        return',
    '      fi',
    '      if [[ "$buffer" == *$\'\\n\' ]]; then',
    '        __sandbox_sessions_emit_payload "$process_id" "$stream" "$buffer"',
    '        buffer=""',
    '      elif (( $' + '{#buffer} > marker_length )); then',
    '        emit_count=$(($' + '{#buffer} - marker_length))',
    '        __sandbox_sessions_emit_payload "$process_id" "$stream" "$' +
      '{buffer:0:$emit_count}"',
    '        buffer="$' + '{buffer:$emit_count}"',
    '      fi',
    '    elif [[ -n "$buffer" ]]; then',
    '      __sandbox_sessions_emit_payload "$process_id" "$stream" "$buffer"',
    '      buffer=""',
    '    fi',
    '  done <> "$fifo"',
    '  __sandbox_sessions_emit_payload "$process_id" "$stream" "$buffer"',
    '}',
    '__sandbox_sessions_exec() {',
    '  local exec_id="$1" cmd_b64="$2" cmd stdout_file stderr_file exit_code',
    '  stdout_file="$__sandbox_sessions_dir/$exec_id.stdout"',
    '  stderr_file="$__sandbox_sessions_dir/$exec_id.stderr"',
    '  cmd=$(echo "$cmd_b64" | base64 -d 2>/dev/null) || { __sandbox_sessions_frame DONE "$exec_id" 1 "" ""; return; }',
    '  rm -f "$stdout_file" "$stderr_file"',
    '  : > "$stdout_file"',
    '  : > "$stderr_file"',
    '  {',
    '    eval "$cmd"',
    '    exit_code=$?',
    '  } < /dev/null > "$stdout_file" 2> "$stderr_file"',
    '  __sandbox_sessions_frame DONE "$exec_id" "$exit_code" "" ""',
    '}',
    '__sandbox_sessions_start_process() {',
    '  local process_id="$1" cmd_b64="$2" cmd stdout_fifo stderr_fifo start_gate stop_marker',
    '  stdout_fifo="$__sandbox_sessions_dir/$process_id.stdout.fifo"',
    '  stderr_fifo="$__sandbox_sessions_dir/$process_id.stderr.fifo"',
    '  start_gate="$__sandbox_sessions_dir/$process_id.start"',
    '  stop_marker="__SANDBOX_SESSIONS_STOP_$process_id"',
    '  cmd=$(echo "$cmd_b64" | base64 -d 2>/dev/null) || { __sandbox_sessions_frame PROCESS_STARTED "$process_id" 0 "" ""; __sandbox_sessions_frame PROCESS_DONE "$process_id" 1 "" ""; return; }',
    '  rm -f "$stdout_fifo" "$stderr_fifo" "$start_gate"',
    '  mkfifo "$stdout_fifo" "$stderr_fifo" "$start_gate" || { __sandbox_sessions_frame PROCESS_STARTED "$process_id" 0 "" ""; __sandbox_sessions_frame PROCESS_DONE "$process_id" 1 "" ""; return; }',
    '  (',
    '    local exit_code stdout_pid stderr_pid command_pid',
    '    __sandbox_sessions_emit_fifo "$process_id" stdout "$stdout_fifo" "$stop_marker" &',
    '    stdout_pid=$!',
    '    __sandbox_sessions_emit_fifo "$process_id" stderr "$stderr_fifo" "$stop_marker" &',
    '    stderr_pid=$!',
    '    (',
    '      IFS= read -r _ < "$start_gate"',
    '      eval "$cmd"',
    '    ) < /dev/null > "$stdout_fifo" 2> "$stderr_fifo" &',
    '    command_pid=$!',
    '    __sandbox_sessions_frame PROCESS_STARTED "$process_id" "$command_pid" "" ""',
    '    printf \'\\n\' > "$start_gate"',
    '    rm -f "$start_gate"',
    '    wait "$command_pid"',
    '    exit_code=$?',
    '    printf \'%s\\n\' "$stop_marker" > "$stdout_fifo"',
    '    printf \'%s\\n\' "$stop_marker" > "$stderr_fifo"',
    '    wait "$stdout_pid"',
    '    wait "$stderr_pid"',
    '    rm -f "$stdout_fifo" "$stderr_fifo"',
    '    __sandbox_sessions_frame PROCESS_DONE "$process_id" "$exit_code" "" ""',
    '  ) &',
    '}',
    '__sandbox_sessions_frame READY session 0 "" ""',
    ''
  ].join('\n');
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}
