/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Sandbox";
	}
	interface Env {
		Sandbox: DurableObjectNamespace<import("./src/index").Sandbox>;
	}
}
interface Env extends Cloudflare.Env {}
