# This image is unique to this repo, and you'll never need it.
# Whenever you're integrating with sandbox SDK in your own project,
# you should use the official image instead:
# FROM docker.io/cloudflare/sandbox:0.6.2-python
FROM cloudflare/sandbox-test:0.6.2-python

# Expose the ports you want to expose
EXPOSE 8080
EXPOSE 3001
