FROM docker.io/cloudflare/sandbox:0.8.0

# Required during local development to access exposed ports
# Override control port with --build-arg BUILD_INTERNAL_SERVER_PORT=<port> if using a custom one
EXPOSE 8080
EXPOSE 8671
