# This image is unique to this repo, and you'll never need it.
# Whenever you're integrating with sandbox SDK in your own project,
# you should use the official image instead:
# FROM docker.io/cloudflare/sandbox:0.5.3
FROM cloudflare/sandbox-test:0.5.3

# Required during local development to access exposed ports
EXPOSE 8080
EXPOSE 3000
