/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: d70ad9fbe15919b5bf8325ca39967c07)
declare namespace Cloudflare {
  interface Env {
    Sandbox: DurableObjectNamespace /* Sandbox */;
  }
}
interface Env extends Cloudflare.Env {}
