/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=examples/artifact-workspace/wrangler.jsonc --include-runtime=false examples/artifact-workspace/worker-configuration.d.ts` (hash: 587731b1938246d236e5d268f5be2785)
interface __BaseEnv_Env {
	S3_ENDPOINT: "https://s3.us-east-1.amazonaws.com";
	S3_REGION: "us-east-1";
	S3_BUCKET: "replace-with-your-artifact-bucket";
	S3_ACCESS_KEY_ID: string;
	S3_SECRET_ACCESS_KEY: string;
	SANDBOX: DurableObjectNamespace<import("./src/index").ArtifactSandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ArtifactSandbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "S3_ENDPOINT" | "S3_REGION" | "S3_BUCKET" | "S3_ACCESS_KEY_ID" | "S3_SECRET_ACCESS_KEY">> {}
}
