/**
 * Template generation for sandbox workers
 */
import type { ContainerConfig } from './config.js';

export interface TemplateOptions {
  workerName: string;
  containers: ContainerConfig[];
  accountId: string;
}

export function generateWranglerToml(options: TemplateOptions): string {
  const { workerName, containers, accountId } = options;

  const containerBindings = containers
    .map(
      (c) => `
[[containers]]
binding = "${c.binding}"
class_name = "Sandbox"
image = "${c.image}"`
    )
    .join('\n');

  return `# Generated by sandbox CLI
name = "${workerName}"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "${accountId}"

# Durable Objects for sandbox state
[[durable_objects.bindings]]
name = "SANDBOX"
class_name = "Sandbox"

[[migrations]]
tag = "v1"
new_classes = ["Sandbox"]
${containerBindings}
`;
}

export function generateWorkerCode(options: TemplateOptions): string {
  return `/**
 * Sandbox Bridge Worker
 *
 * Generated by: sandbox deploy
 * Worker: ${options.workerName}
 *
 * This worker provides HTTP access to sandboxed containers.
 */
import { createBridge, type BridgeEnv } from '@cloudflare/sandbox/bridge';

interface Env extends BridgeEnv {
  SANDBOX_API_KEYS: string; // Comma-separated list of valid API keys
}

// Validate API key from environment
function getApiKeys(env: Env): string[] {
  const keys = env.SANDBOX_API_KEYS || '';
  return keys.split(',').map((k) => k.trim()).filter(Boolean);
}

// Create the bridge handler
const bridge = createBridge({
  validateApiKey: (apiKey, env: Env) => {
    const validKeys = getApiKeys(env);
    return validKeys.includes(apiKey);
  }
});

export { Sandbox } from '@cloudflare/sandbox';

export default bridge;
`;
}

export function generateDockerfile(type: 'base' | 'python' | 'full'): string {
  switch (type) {
    case 'python':
      return `FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \\
    python3 python3-pip \\
    curl git \\
    && rm -rf /var/lib/apt/lists/*

# Install common Python packages
RUN pip3 install --no-cache-dir numpy pandas matplotlib

WORKDIR /workspace
`;

    case 'full':
      return `FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \\
    python3 python3-pip \\
    nodejs npm \\
    curl git wget jq \\
    && rm -rf /var/lib/apt/lists/*

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

# Install common packages
RUN pip3 install --no-cache-dir numpy pandas matplotlib

WORKDIR /workspace
`;

    default:
      return `FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \\
    curl git \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
`;
  }
}

export function generatePackageJson(workerName: string): string {
  return JSON.stringify(
    {
      name: workerName,
      version: '0.0.1',
      type: 'module',
      scripts: {
        dev: 'wrangler dev',
        deploy: 'wrangler deploy',
        tail: 'wrangler tail'
      },
      dependencies: {
        '@cloudflare/sandbox': '^0.6.0'
      },
      devDependencies: {
        wrangler: '^3.0.0',
        typescript: '^5.0.0'
      }
    },
    null,
    2
  );
}

export function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        lib: ['ES2022'],
        types: ['@cloudflare/workers-types'],
        strict: true,
        skipLibCheck: true,
        noEmit: true
      },
      include: ['src/**/*.ts']
    },
    null,
    2
  );
}
