# syntax=docker/dockerfile:1

# FROM docker.io/ghostwriternr/cloudflare-sandbox:0.0.5
FROM my-sandbox-base:latest

EXPOSE 8080
EXPOSE 3001

# Run the same command as the original image
CMD ["bun", "index.ts"]
