name: Prerelease

on:
  push:
    branches:
      - main

jobs:
  prerelease:
    if: ${{ github.repository_owner == 'cloudflare' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Modify package.json version
        run: npx tsx .github/version-script.ts

      - name: Resolve workspace dependencies
        run: npx tsx .github/resolve-workspace-versions.ts

      - name: Run type checking
        run: npm run typecheck
        
      - name: Run linting
        run: npm run check
        
      - name: Build packages
        run: npm run build
        
      - name: Run full test suite
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (beta)
        run: npm run docker:publish:beta --workspace=@cloudflare/sandbox

      - run: npm publish --tag beta --access public
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        working-directory: packages/sandbox
