name: Test Suite
permissions:
  contents: read

on:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: npm ci
      - run: npm run build

      - name: Run sandbox unit tests
        run: |
          set +e
          timeout --preserve-status 30 npm run test -w @cloudflare/sandbox > sandbox_test.log 2>&1
          EXIT_CODE=$?
          cat sandbox_test.log

          if grep -q "Test Files.*passed" sandbox_test.log && grep -q "Tests.*passed" sandbox_test.log; then
            echo "Sandbox tests passed"
            if [ $EXIT_CODE -eq 124 ] || [ $EXIT_CODE -eq 143 ]; then
              echo "::warning::Killed due to workerd shutdown hang (known vitest-pool-workers issue)"
            fi
            exit 0
          else
            echo "Sandbox tests failed"
            exit 1
          fi

      - name: Run container unit tests
        run: npm run test -w @repo/sandbox-container

  # E2E tests
  e2e-tests:
    runs-on: ubuntu-latest
    needs: quality-checks
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: npm ci
      - run: npm run build

      # Build Docker image for test worker (needed before deployment)
      - name: Build test worker Docker image
        run: npm run docker:local -w @cloudflare/sandbox

      # Set worker name
      - name: Set worker name
        id: worker-name
        run: |
          echo "worker_name=sandbox-e2e-test-worker-${{ github.ref_name }}" >> $GITHUB_OUTPUT

      # Deploy test worker
      - name: Deploy test worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name ${{ steps.worker-name.outputs.worker_name }}
          workingDirectory: tests/e2e/test-worker

      # Construct worker URL from worker name
      - name: Get deployment URL
        id: get-url
        run: |
          echo "worker_url=https://${{ steps.worker-name.outputs.worker_name }}.agents-b8a.workers.dev" >> $GITHUB_OUTPUT

      # Run E2E tests against deployed worker
      - name: Run E2E tests
        run: npx vitest run --config vitest.e2e.config.ts
        env:
          TEST_WORKER_URL: ${{ steps.get-url.outputs.worker_url }}
          CI: true
