name: Test Suite

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run type checking
        run: npm run typecheck
        
      - name: Run linting
        run: npm run check
        
      - name: Run unit tests
        run: npm run test:unit
        working-directory: packages/sandbox
        
      - name: Run integration tests
        run: npm run test:integration
        working-directory: packages/sandbox
        
      - name: Setup Docker for container tests
        uses: docker/setup-buildx-action@v3
        
      - name: Run container tests
        run: npm run test:container
        working-directory: packages/sandbox
        
      - name: Run E2E tests
        run: npm run test:e2e
        working-directory: packages/sandbox
        
      - name: Generate coverage report
        run: npm run test:coverage
        working-directory: packages/sandbox
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./packages/sandbox/coverage/lcov.info
          fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build sandbox package
        run: npm run build
        working-directory: packages/sandbox
        
      - name: Build Docker image
        run: npm run docker:local
        working-directory: packages/sandbox

  example-test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build sandbox package
        run: npm run build
        working-directory: packages/sandbox
        
      - name: Test example application
        run: |
          npm ci
          npm run build
        working-directory: examples/basic